export const HomeObjOne = {
  id: "story",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Please work :(",
  headLine: "boi",
  description: "WHYY YOU DOO THIS BOIII",
  buttonLabel: "ahhhh",
  imgStart: false,
  img: "/images/story.svg",
  alt: "yooooo",
  dark: true,
  primary: true,
  darkText: false,
};

export const HomeObjTwo = {
  id: "contact",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Please work :(",
  headLine: "boi",
  description: "WHYY YOU DOO THIS BOIII",
  buttonLabel: "ahhhh",
  imgStart: true,
  img: "/images/story.svg",
  alt: "yooooo",
  dark: true,
  primary: true,
  darkText: true,
};
